### ISSUE TITLE
oni-ml: scp command causes a nested FDATE folder

### ISSUE THREAD

**Issue by natedogs911** [Open-Network-Insight/open-network-insight#70]
when running ml_ops.sh the scp command at the end of the script copies the files to the UINODE,
however it creates a nested date folder (i.e. /home/someuser/ipython/user/20160603/20160603/ ) instead of copying the files directly the ipython/user folder.

**Comment by ronkuhl** [comment]
I think the issue is caused by having FDATE at the end of RPATH
I don't know where else RPATH is used, so I just added a new variable to the .conf file --  
OAPATH - same as RPATH but no FDATE at the end
OAPATH=${LUSER}/ipython/user/

And modified the "copy to OA" command at the end of ml_ops.sh
rsync -av ${LPATH} ${UINODE}:${OAPATH}

**Comment by saiganji** [comment]
I assume this issue is not needed anymore as the new results of ML are going to HDFS. Correct me I am wrong. @natedogs911

**Comment by rabarona** [comment]
That's correct @saiganji.

**Comment by natedogs911** [comment]
That's correct, thank you
