### ISSUE TITLE
Ingest configuration help

### ISSUE THREAD

**Issue by thealy** [Open-Network-Insight/open-network-insight#98]
Hi- We are trying to turn up a Spot installation and are making progress based on the Deployment Guide. I believe we have all the Ingest prerequisites satisfied, but I'm confused about the Ingest pipeline configuration, specifically what to put in "collector_path":"/path_to_flow_collector" and what it means.

So I have a NetFlow sources, currently going to custom app which parses and stores as AVRO in HDFS. Now I need to ??? feed this to nfdump, and place the resulting files in the "/path_to_flow_collector" directory on the ingest machine? 

In relation to ingest workers: Is this a thread, or a second ingest machine? (we have allocated two for ingest)

Any help much appreciated.

**Comment by EverLoSa** [comment]
Hi @thealy 

The "collector_path" is a directory in the local file system (where the ingest is running) , the idea of this "collector_path" is that you can put there the files that you want to ingest (currently supported nfcapd) you dont need to do anything else  beside to putting the files there, the ingest will execute the nfdump to convert the files to Avro format and store them in Hive.

Are you storing your files in hive ? , If you do then we can review your schema ,  because  Machine Learning reads from Hive with a specific schema. if yours is different there might be a problem with machine learning.

Talking about the workers, the workers  are daemons running in the same machine , these daemons read from Kafka to transform/ingest the files into HDFS/HIVE

Does that make sense ?

**Comment by thealy** [comment]
OK, making progress. Have the files coming in now, understand the config. Managed to get master started with two workers. Re-checking my Kafka install, as getting error saying Errors.NoBrokersAvailable().

**Comment by natedogs911** [comment]
where is the broker located? 
if it's on the same server you are running the ingest framework from you may want to specify the loopback address (127.0.0.1).

**Comment by thealy** [comment]
Kafka was installed on another system in the cluster, and I have since installed it to the system where I am configuring ingest. The system is actually receiving netlfow files and storing them in HDFS, despite the error messages. But a script called kafka-topics.sh is failing because there is no kafka-topics (note no .sh suffix) in the path; I'm beginning to think this is in Cloudera kafka but not "regular" Apache Kafka that I'm using - my cluster is MapR, not Cloudera.

**Comment by thealy** [comment]
Data is now being written to HDFS in the Hive tables, but the first Map/Reduce job is failing due to some sort of permissions issue. 
2016-10-12 18:12:32,1735 ERROR Client fs/client/fileclient/cc/client.cc:6746 Thread: 6512 GetGid failed, could not get groupinfo for group 1002, error: Invalid argument(22)
chgrp: changing ownership of 'maprfs:///user/spot/flow/hive/y=2016': Could not set owner/group null/1002 for path maprfs:///user/spot/flow/hive/y=2016

Where the group:user is: (My "solution user" is "spot")
drwxr-xr-x   - root spot          1 2016-10-12 14:12 /user/spot/flow/hive/y=2016/m=10

Should the scripts on the oni-ingest be running as spot rather than root?

**Comment by EverLoSa** [comment]
Hi @thealy.

Yes the ingest must run with spot user.

Also before to start the ingest "spot" user ,please change the ownership of the pipeline folder to spot user (i.e. /user/spot/flow).

Please join our slack channel to provide you  with more support: http://slack.apache-spot.io/

**Comment by thealy** [comment]
OK, I got signed up with Slack/Spot, so I will post my questions over there. I will make the changes to run as the "spot" user, and check the pipeline folder ownership.
Thanks for your help.
